#!/bin/bash
# ---------------------------------------------------------------------------
#  Intel Concurrent Collections for Haskell
#  Copyright (c) 2010, Intel Corporation.
# 
#  This program is free software; you can redistribute it and/or modify it
#  under the terms and conditions of the GNU Lesser General Public License,
#  version 2.1, as published by the Free Software Foundation.
# 
#  This program is distributed in the hope it will be useful, but WITHOUT
#  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for
#  more details.
# 
#  You should have received a copy of the GNU Lesser General Public License along with
#  this program; if not, write to the Free Software Foundation, Inc., 
#  51 Franklin St - Fifth Floor, Boston, MA 02110-1301 USA.
# ---------------------------------------------------------------------------

ntimes=`dirname $0`/ntimes

times=`$ntimes $*`
CODE=$?
if [ "$CODE" != "0" ];
then exit $CODE
fi

lines=`echo $times | xargs -n1 echo  | wc -l`
half=$((($lines+1)/2))

echo "Median time (of $lines): " >> /dev/stderr
#echo "Median time of: $times" >> /dev/stderr

MIN=`echo $times | xargs -n1 echo  | sort -n | head -n1`
MED=`echo $times | xargs -n1 echo  | sort -n | head -n$half | tail -n1`
MAX=`echo $times | xargs -n1 echo  | sort -n | tail -n1`

echo $MIN $MED $MAX
