#!/bin/bash

# Ported from Haskell CnC script (BSD license)

ntimes=`dirname $0`/ntimes

times=`$ntimes $*`
CODE=$?
if [ "$CODE" != "0" ];
then exit $CODE
fi

lines=`echo $times | xargs -n1 echo  | wc -l`
half=$((($lines+1)/2))

echo "Median time (of $lines): " >> /dev/stderr
#echo "Median time of: $times" >> /dev/stderr

MIN=`echo $times | xargs -n1 echo  | sort -n | head -n1`
MED=`echo $times | xargs -n1 echo  | sort -n | head -n$half | tail -n1`
MAX=`echo $times | xargs -n1 echo  | sort -n | tail -n1`

echo $MIN $MED $MAX
